### ISSUE TITLE
Midi assignment config

### ISSUE THREAD

**Issue by jackwlee01** [PO-MIDI-Adapter/midi-adapter-sofware#3]
Just got my midi adapter and have been loving it so far. It's awesome!

Could you please provide more information about the configuration.

I have hooked it up to my Deluge and the default assignments scatter the notes around.

Are you able to provide an example config.fcg file?

**Comment by HanYangZhao** [comment]
Of course! You'll just need to update the file on the SD card

https://github.com/PO-MIDI-Adapter/midi-adapter-software/blob/master/config.cfg

midi_note_1 -> PO_BUTTON_1
midi_note_2 -> PO_BUTTON_2
midi_note_3 -> PO_BUTTON_3
midi_note_4 -> PO_BUTTON_4
midi_note_5 -> PO_BUTTON_5
midi_note_6 -> PO_BUTTON_6
midi_note_7 -> PO_BUTTON_7
midi_note_8 -> PO_BUTTON_8
midi_note_9 -> PO_BUTTON_9
midi_note_10 -> PO_BUTTON_10
midi_note_11 -> PO_BUTTON_11
midi_note_12 -> PO_BUTTON_12
midi_note_13 -> PO_BUTTON_13
midi_note_14 -> PO_BUTTON_14
midi_note_15 -> PO_BUTTON_15
midi_note_16 -> PO_BUTTON_16
midi_note_sound -> PO_BUTTON_SOUND
midi_note_pattern -> PO_BUTTON_PATTERN
midi_note_bpm -> PO_BUTTON_BPM
midi_note_special -> PO_BUTTON_SPECIAL
midi_note_fx -> PO_BUTTON_FX
midi_note_play -> PO_BUTTON_PLAY
midi_note_write -> PO_BUTTON_WRITE

**Comment by jackwlee01** [comment]
Fantastic, thanks!
